name: Python CICD Kata
run-name: Python CICD Kata
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version-file: "pyproject.toml"
      - run: ruff format .
